### ISSUE TITLE
Change Tempo crash (Audacity 3.0.2 for Windows)

### ISSUE THREAD

**Issue by fulvio314** [audacity/audacity#1272]
**Describe the bug**
Applying 'change tempo' causes crash, no error messages, just audacity window disappear.

**To Reproduce**
1. Generate Tone sinus 300Hz, 0,4 amplitude, 5"
2. Move track back a little, so the track ends at 4,5"
3. Apply 'change tempo' 5% (high quality ON)
4. The progress bar starts and when reaches 3/4 audacity closes without any error message

**Additional information:**
 - OS: Windows 10 Pro build 19041.1083, 64 bit (updated 2021 july 08)
 - Pentium dual core 3.2GHz, 5GB RAM
 - Audacity 3.0.2

**Comment by SteveDaulton** [comment]
I believe that this is fixed in our current code: https://github.com/audacity/audacity/commit/d0ff48f3bde0c35905157036cdc0ff9532d469a3

**Comment by MartinHotmann** [comment]
Still have this bug in the very latest version (v3.1.3).
My audio file goes for about 1:30min and crashes ALL the times.
