### ISSUE TITLE
Windows: Transport toolbar has black dots at the corners of its buttons

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1768]
**Describe the bug**
In the latest mater alpha (Redo images for new loop button properly CMake Build #2747)  the Transport toolbar has black dots at the corners of its buttons where the nice rounded corners should be.

**To Reproduce**
1. Launch latest alpha - audacity-win-3.1.0-alpha-20210927+1fe4d70-64bit
2. Observe: square corners with black dots
3. launch earlier alpha - audacity-win-3.1.0-alpha-20210927+25d7d1d-64bit
4. Observe: nice rounded corners with no ugly black dots
5. Launch 3.4,0
6. Observe: nice rounded corners with no ugly black dots

**Expected behavior**
Transport toolbar buttons to have nice rounded corners with no black dots

**Screenshots**
1)  Latest alpha  audacity-win-3.1.0-alpha-20210928+1fe4d70-64bit
![image](https://user-images.githubusercontent.com/50205984/135103969-e380547b-0e7e-4c61-a0ed-4f5bce2d51fd.png)

2) Alpha from yesterday
![image](https://user-images.githubusercontent.com/50205984/135104413-43491659-5fc1-42da-86d4-7420a6310418.png)

3) Audacity 3.0.4
![image](https://user-images.githubusercontent.com/50205984/135104714-3d532657-a039-4629-adbe-239a926354b2.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version@ latest alpha audacity-win-3.1.0-alpha-20210927+25d7d1d-64bit

**Additional context**
Not tested on other platforms

**Comment by petersampsonaudacity** [comment]
Note too the corruption of the Tools toolbar with overlapping buttons:
![image](https://user-images.githubusercontent.com/50205984/135107741-d80f57a8-e748-47ab-a889-be4293669add.png)

**Comment by petersampsonaudacity** [comment]
Note that the Play button ad the Play-at-Speed button both have the bottom of their green triangle truncated - this is a regression on earlier Audacity
![image](https://user-images.githubusercontent.com/50205984/135113281-62bebd0f-4180-4cab-b410-3423d81c67b7.png)
This is a W10 image - but the same is true on Mac as well

**Comment by Paul-Licameli** [comment]
@JamesCrook help me out here.  I did all the folderol in Theme preferences that one does to update the ThemesAsCeeCode, but I did it on a Mac.  Does it make a difference ?

**Comment by JamesCrook** [comment]
Does your image editor properly support transparency?
If you edited the png without preserving transparency, that's one way to get the black dots.

**Comment by petersampsonaudacity** [comment]
> 
> 
> Note that the Play button ad the Play-at-Speed button both have the bottom of their green triangle truncated - this is a regression on earlier Audacity 

I have now logged this separately as regression issue #1792

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/135836896-6fb5c446-cee9-4a5e-b192-1e3335bc0825.png)
NB: In addition to the black dots, the grey tone of the background also has shifted towards something browner

**Comment by Paul-Licameli** [comment]
> Does your image editor properly support transparency?
> If you edited the png without preserving transparency, that's one way to get the black dots.

I did nothing involving an image editor.  I saved images using Theme preferences, and added image files, and rebuilt with changed AllThemeResources.h, and loaded files, and output the "sourcery".

Or I think I did.  I may need to redo it all.

**Comment by Paul-Licameli** [comment]
> > Does your image editor properly support transparency?
> > If you edited the png without preserving transparency, that's one way to get the black dots.
> 
> I did nothing involving an image editor. I saved images using Theme preferences, and added image files, and rebuilt with changed AllThemeResources.h, and loaded files, and output the "sourcery".
> 
> Or I think I did. I may need to redo it all.

wxImage objects are supposed to be platform-independent representations of RGB and Alpha data, right?  (not wxBitmap.). I thought all the code I was exercising is only doing wxImage manipulations.

**Comment by JamesCrook** [comment]
The background colour shift suggests the "Blend system and Audacity Theme" option was enabled when using the unmodified theme before saving it out.
https://alphamanual.audacityteam.org/man/Interface_Preferences

If you're doing work on the theme, it shouldn't be.

**Comment by Paul-Licameli** [comment]
> The background colour shift suggests the "Blend system and Audacity Theme" option was enabled when using the unmodified theme before saving it out. https://alphamanual.audacityteam.org/man/Interface_Preferences
> 
> If you're doing work on the theme, it shouldn't be.

That doesn't explain it.  The preference was on, but when I step through the code in `ThemeBase::RecolourTheme`, I see it only affects button backgrounds, and it was skipped because `d < 40`

**Comment by petersampsonaudacity** [comment]
> I don't think we're allowed to use those glossy mac buttons on Windows (or Linux). They are apple-button backgrounds.

OOH  - that's a pity

**Comment by Penikov** [comment]
I've extracted the truncated triangle issue to the other bug: #1907

Black dots are fixed.

**Comment by SteveDaulton** [comment]
I'm still seeing this bug with Audacity 3.1.0-alpha-20211021(Commit Id: b21ac7)

![transport](https://user-images.githubusercontent.com/11681097/138329938-3658ce5f-881c-44e9-87b2-f1ec67c7ce81.png)
