### ISSUE TITLE
Build instructions fail on Arch linux

### ISSUE THREAD

**Issue by adrian-stephens** [audacity/audacity#2390]
Following the build instructions, the build fails with reference to a missing
        NotFoundException: Not found: https://sourceforge.net/projects/portmedia/files/portmedia-code-r234.zip

**To Reproduce**
Install latest Arch linux and prerequisites: python3, python-pip, conan, cmake, git, gtk2, alsa-lib, ffmpeg, jack2, uuid
Follow instructions in BUILDING.md, including a git clone of the latest source.
Observe cmake step (release build) fails:
"portmidi/r234: Configuring sources in /home/adrians/.conan/data/portmidi/r234/_/_/source
ERROR: portmidi/r234: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version])
        NotFoundException: Not found: https://sourceforge.net/projects/portmedia/files/portmedia-code-r234.zip
CMake Error at cmake-proxies/cmake-modules/conan.cmake:638 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:255 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:277 (_conan_install)
  CMakeLists.txt:554 (resolve_conan_dependencies)"

**Expected behavior**
cmake completes without error

**Additional information (please complete the following information):**
Latest (as of 2022-01-07) version of Arch linux and dependencies.  Kernel 5.15.
Latest git clone of audacity master.
cmake 3.22.1

**Additional context**
This is not a new problem.   I wanted to build 3.0.5,  which is the last version with acceptable noise reduction performance and doesn't have the annoying set loop region hijack of the "play from click" function.   I built this version successfully in Ubuntu a couple of weeks ago.   I got the same error on 3.0.5 as reported above,  so I tried building from the top of trunk with the same result.

I also tried setting all the -Daudacity_use_port* variables to system with no effect.

**Comment by crsib** [comment]
This is fixed already. Please run `conan remove portmidi` and try building again

**Comment by adrian-stephens** [comment]
Thank you.  I'll try that.  

Dear crsib and LWinterberg, I appreciate the support.  But I respectfully believe the issue is not yet fixed in the sense that the current build instructions do not work for Arch.
