### ISSUE TITLE
A clip needs to be selected for the context menu to enable "Rename Clip"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3101]
**Describe the bug**
A clip needs to be selected for the context menu to enable "Rename Clip".

Also if a clip is selected and you right-click in a different clip the "Rename Clip" will be applied to the selected clip and not the clip that has been right-clicked in

**To Reproduce**

Use Case 1
1. Get some audio (single clip)
2. ensure it is not selected
3. right-click in the clip
4. **Observe:** in the context menu "Rename Clip..." is grayed out and inoperable
5. Select the whole clip (must be the whole clip)
6. right-click in the clip
7.  **Observe:** in the context menu "Rename Clip..." is now not grayed out and is operable

Use Case 2
1. Get two clips
2. select the first clip
3. right click in the second clip
4. **Observe:** it is the name of the first clip that is opened for editing _**NOT**_ the name of the second clip

**Actual behavior**
See above.

**Expected behavior**
a) the clip to be renamed should b=not need to be selected
b) the clip name opened for editing should be the one that is right-clicked in (this would then be consistent with the "Split Clip" command in the same context menu.

**Screenshots**
### Use Case 1
![image](https://user-images.githubusercontent.com/50205984/174295054-ce2ba08d-16c3-42a0-a0a6-efa411949dee.png)

### Use Case 2
![image](https://user-images.githubusercontent.com/50205984/174295814-c6455f15-5d8c-4fe0-8acf-07a967d16398.png)

**Additional information (please complete the following information):**
 - OS: W10 (but assume all OS
 - Version:  3.2.0 alpha and 3.1.3

**Additional context**
See also #3103

**Comment by petersampsonaudacity** [comment]
An alternative would be to rename the commands in the Clip Context menu and in the Edit menu to
**Rename Selected Clip**

**Comment by Ryan-Miller-Audacity** [comment]
I was able to reproduce these behaviors as described in the summary on both MacOS and Windows 10.

**Comment by petersampsonaudacity** [comment]
This remains the case in the latest (today's) 3.2.0 release build:  
https://github.com/audacity/audacity/actions/runs/3081056287

**Comment by petersampsonaudacity** [comment]
See also:   #3704

**Comment by ianalarina** [comment]
resolved in scope of issue #3704

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.3.0 beta

@ianalarina @Ryan-Miller-Audacity @crsib 

This does **_NOT_** appear to be fixed.  I still see the **Use Case 1** and **Use Case 2** behaviors outlined in the initial post in this thread.

**Comment by petersampsonaudacity** [comment]
See this recent Forum thread:
**Clip name editing**
https://forum.audacityteam.org/t/clip-name-editing/81510

**Comment by LWinterberg** [comment]
This is fixed in Audacity 4
