### ISSUE TITLE
Input & Playback metering toolbars: UI enhancements

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3627]
### Your idea

- [x] make metering toolbars slightly longer
- [ ] vertically stack meters by default (so they stay stacked when widening the window)

### 1. Make the width of the metering toolbars slightly larger

The default width of those two meters is too narrow and only fits 12dB increments. Let's make it a tad wider so that the increment will become 6 dB:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/70063970/190448242-4d62a0c4-3717-4737-a625-9968691fbb0b.png">

### 2. Keep the arrangement of both toolbars the same way as after config reset, i.e. one above the other

When resetting the config by **Tools > Reset Configuration**, the toolbars get placed one above the other. Double-click Audacity window to maximize - and you'll get them placed side by side:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/70063970/190448737-732b7c0b-fed0-4506-84fa-0e1f90e72d1c.png">

Let's keep the placement the same way as it is initially, i.e. one above another: input meter on top, playback meter below.

### Problem to be solved

Oddly looking UI

### Additional context

Confirmed with @Tantacrul

**Comment by petersampsonaudacity** [comment]
@Tantacrul A big +1 for @dozzzzer 's   point no. 1 regarding the default with of the meters.

Especially as we now have blank space in the upper tooldock to the right of the meters:
![image](https://user-images.githubusercontent.com/50205984/190578814-26e7b713-cee4-408d-84ab-873737e38193.png)

**Comment by Tantacrul** [comment]
@petersampsonaudacity - yes, I've bumped it to this release.

**Comment by dozzzzer** [comment]
Verified. The default size of the meters is now showing 6 dB increments.
Point no. 2 from the description is still to be fixed though.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer 

Surely this was fixed for 3.2 already - the current 3.2.11 at default settings shows:
![image](https://user-images.githubusercontent.com/50205984/196903554-7aee3f17-beab-42ea-bbdd-46d844942dfb.png)

**Comment by LWinterberg** [comment]
part 2 - vertically stack meters by default (so they stay stacked when widening the window) - is not yet fixed. They're side-by-side and get stacked on the default windowed size, but unstack once you go fullsscreen. Goal is to have them be stacked even in fullscreen.

**Comment by petersampsonaudacity** [comment]
Effectively it looks like what you are going back to is to make the pair of meters a single double-height toolbar just as we had in Audacity many moons ago before we eventually separated them

Personally I always prefer (and need) to have to Recording meter much larger than my Playback  meter.  For me the Recording meter is **_very_** important and the Playback meter is largely irrelevant.

**Comment by dozzzzer** [comment]
> will the user still be able to move and resize each (or even hide) each meter independently?

Yes for moving and resizing independently, though not quite sure about hiding.
