### ISSUE TITLE
VST2: Dry signal during first-time playback with the effect added in the sidebar and its GUI opened

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3843]
### Steps to reproduce

1. Cmd (Ctrl) + N to create a new project
2. Have some audio
3. In the sidebar, select [TAL Reverb 2](https://plugins4free.com/plugin/683/)
4. Open its dialog
5. Load the Dull Plate preset
6. Play the track
7. Stop
8. Now play the track again

### Expected behavior

The effect is applied correspondingly.

### Actual behavior

The output signal is dry when hitting Play for the first time after showing the UI of the effect.
When playing the track again, the output signal turns to wet.

https://user-images.githubusercontent.com/70063970/197574786-f93c411c-e98e-40af-b8c6-71d101bbfa37.mp4

### Audacity Version

The build [from here](https://github.com/audacity/audacity/actions/runs/3312593613)

### Operating system

macOS, Windows 11

**Comment by pietro68** [comment]
So far it looks like this is specific to TAL-reverb, I can not reproduce it using BlueCat Chorus

**Comment by dozzzzer** [comment]
Commit: 852a4b4de6cce99d549a33e974a83d38c923206a
GH job: https://github.com/audacity/audacity/actions/runs/3429017268
OS: macOS 13.0

Plugin: Renegate by Auburn Sounds
The issue exists: No

Plugin: Deegain
The issue exists: No

Plugin: BassDrive by Tonelib
The issue exists: No

Plugin: BC Chorus 4
The issue exists: No

Plugin: Valhalla Supermassive
The issue exists: No

Plugin: TAL Reverb-2
The issue exists: Yes

@Paul-Licameli @pietro68

**Comment by Ryan-Miller-Audacity** [comment]
My findings are the same as others. The issue only seems to occur for TAL Reverb 2, even testing other plugins from TAL did not show this issue.

Commit: [https://github.com/audacity/audacity/commit/852a4b4de6cce99d549a33e974a83d38c923206a 852a4b4]
GH job: https://github.com/audacity/audacity/actions/runs/3429017268
OS: Windows 10

Plugin: MReverb by Melda Productions
The issue exists: No

Plugin: SPL Mo-Verb Plus by Plugin Alliance
The issue exists: No

Plugin: TAL Dub III  by Togu Audio Line (TAL)
The issue exists: No

Plugin TAL-Chorus-LX by Togu Audio Line (TAL)
The issue exists: No

Plugin: TAL-Reverb-3 by Togu Audio Line (TAL)
The issue exists: No

Plugin: ValhallaDelay
The Issue exists: No

Plugin: TAL Reverb-2
THe issue exists: Yes

**Comment by dozzzzer** [comment]
@Paul-Licameli 
The issue persists in the commit https://github.com/audacity/audacity/commit/ea8aec68444873520335910144336cb6d38bc81d

Moving back to `To Do`

**Comment by Paul-Licameli** [comment]
@dozzzzer I claim that this is fixed on macOS after commit ea8aec68444873520335910144336cb6d38bc81d.  Do you agree?

Should the title be updated to indicate it is now Windows only?  (Linux?)

**Comment by dozzzzer** [comment]
@Paul-Licameli I'm checking against https://github.com/audacity/audacity/commit/932d7ae94f1535c518cbb2faa24a151806c8d60e and still see this bug not being fixed

**Comment by pietro68** [comment]
New insight: 

After you load the Dull Plate preset, if you click on the effects's gui "Stereo Input" label switch so to de-enable it, and then press play, you will hear the effect at first play.

**Comment by dozzzzer** [comment]
Verified on macOS and Windows 11
