### ISSUE TITLE
Crash when tweaking track's gain level after restart 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3997]
### Steps to reproduce
1. Generate > Noise
2. Set the gain to any negative value, e.g. -24.0 dB
3. Press the Space key to play the track
4. Wait a few seconds and then press the Space key again
5.  Ctrl (Cmd) + W > No
6. Generate > Noise
7. Pull the gain slider again to a negative value
(optional) 8. Repeat steps 5-7

### Expected behavior

No crash

### Actual behavior

https://user-images.githubusercontent.com/70063970/204854408-d3b48eb8-8a81-4ce0-88b5-ba673cc79533.mp4

Crash:
[Audacity_dbgrpt-5232-20221130T170906.zip](https://github.com/audacity/audacity/files/10124975/Audacity_dbgrpt-5232-20221130T170906.zip)

### Audacity Version

https://github.com/audacity/audacity/actions/runs/3584400454

### Operating system

Windows, macOS

**Comment by Paul-Licameli** [comment]
The crash stack involves ASlider and LWSlider.  @ksoze95 and @vsverchinsky  changed those files recently.

This is a recent regression.  The bug is absent at commit 8e28baed6d24f71e1186b5d292144ce173e19b87

**Comment by Paul-Licameli** [comment]
I think this will bracket to 8e28baed6d24f71e1186b5d292144ce173e19b87..1f1f10e103af8ca387b136e65e4478cdd7b09134

**Comment by Ryan-Miller-Audacity** [comment]
Verified on Windows 10 and MacOS via PR #4001 (build: https://github.com/audacity/audacity/actions/runs/3591832691).

**Comment by Paul-Licameli** [comment]
This fix caused another crash, now fixed by #4028.  I think this issue should be verified again with that PR branch.

**Comment by Ryan-Miller-Audacity** [comment]
Re verified in the buidl for PR #4028. Confirmed the crash is still fixed on both MacOS and Windows.
