### ISSUE TITLE
Improve zooming behavior

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4212]
Zooming with the scrollwheel in Audacity got identified as being much too quick and unrestricted, resulting in easy overscrolling into either the sample level or the days-and-weeks level.

Another issue is that zooming near the start of the track may accidentally cause vertical zooms instead, as reported in #5096.

- [x] Set the zoom factor for mousewheel scrolling to 4th-root of 2. The button zooms stay as-is. #4243 
- [x]  Limit the range accessible to the user to 2x the project length. (so for a 10 minute project, the range between 0:00:00 and 0:20:00 can be reached). 
- [x]  When scrolling with the wheel, always center zooming in and out on the mouse cursor, with two exceptions:  
  a) if zooming would reveal an area beyond the limit, the zoom center gets moved (this is the same behavior as observed currently at the 0:00:00 mark)  
  b) (nice-to-have) when the cursor is within 5px of a range selection edge or point selection, center the zoom on the edge/point instead and align the center with the cursor
- [ ] Add a zoom sensitivity preference
- [x] When changing tempo, adjust the zoom such that the current view stays visible despite taking up different amounts of time

For clarity, there currently are some rules in place when zooming with selections and one which attempts to keep at least 1px of project visible in the zoom window at all times. These rules can be removed. 

Initial design link: https://zpl.io/ewND3ZN

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @LWinterberg 's latest branch build:  audacity-win-3.3.0-alpha-20230119+04efd88-x64

1) the zoom factor for scroll zooming is now less aggressive with 1.25x scale factor rather than the 2x

2) However, the Zoom In/Out buttons in the Edit toolbar and the View >Zoom > Zoom In/Out both still work with the 2x zoom factor.  This is intentional and is unlikely to be changed.

**Comment by Tantacrul** [comment]
I think point 3 and 4 need just a very simple visual to make sure the desired effect is clear.

Perhaps @DilsonsPickles can aid here?

**Comment by petersampsonaudacity** [comment]
@Tantacrul @DilsonsPickles  Maybe there should be a limit to zoom out such that the audio is always visible.

This, for an example use case, is a thirty-second chirp after using the zoom out button 10 times:
![image](https://user-images.githubusercontent.com/50205984/214846693-8eb7be24-eed7-4e36-8c85-dcd0e125f333.png)

**Comment by LWinterberg** [comment]
See point 2 @petersampsonaudacity

**Comment by petersampsonaudacity** [comment]
@LWinterberg  the way I read it point 2 is an upper-wall only - or have I misunderstood ?

**Comment by Paul-Licameli** [comment]
I suggest a multiplier of 2 ^ 1/n where n is a small integer.  i.e. square (or cube or fourth) root of 2.

An irrational number, but then, repeating n times gives an exact twofold change which can be convenient.

**Comment by petersampsonaudacity** [comment]
I've just run this past my "Mystery-Shopper" - she too thinks the less aggressive mouse zoom is much better ...

**Comment by BenMcLean** [comment]
Zoom factor / mouse wheel sensitivity should be a configurable option, not just one-size-fits-all. Different people will have their own preferences on this as well as physically different input devices. Games have this, why not editing software too? :)

**Comment by EriksR1** [comment]
"Add a zoom sensitivity preference"
hopefully this gets added

**Comment by LWinterberg** [comment]
This is fixed in Audacity 4

**Comment by EriksR1** [comment]
It's not fixed, zooming from a 5 minute track still takes 14 full scrolls to get to sample level. And zoom speed still isn't adjustable. Then if you want to zoom in on another spot, 14 more scrolls out and 14 more scrolls back in. With old behaviour it was quick and seamless to navigate with scrollwheel +ctrl/shift. Maybe a few scrolls.

**Comment by kryksyh** [comment]
@EriksR1 Do zoom presets solve your issue of quickly switching between two distinct zoom levels?

<img width="895" height="681" alt="Image" src="https://github.com/user-attachments/assets/79cada40-cf4c-4d0d-a76d-45e5d6b6a8c6" />

**Comment by EriksR1** [comment]
I have the Zoom state 2 set up to an approx convenient state, I'm still not used to using it, but the zoom toggle was an option even in old Audacity 3, I believe. It's the next best thing, I suppose, to avoid 14 scrolls at a time, but it has downsides. Like: while you are scrolling in you're 'keeping track of' which part of the track you're looking at. With a toggle you can lose bearings. Using the scrollwheel + ctrl/shift combos I don't even need an interface button. Old zoom speed allowed for quick zooming and navigating to different parts. This would be fixed with a zoom speed setting.
