### ISSUE TITLE
Clips can be negatively stretched to (apparently) zero length, making them irretrievable

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5145]
### Bug description

It is possible to negatively stretch a clip to (apparently) zero length, making it irretrievable

### Steps to reproduce

1. create a 30 second chirp
2. zoom out one level
3. drag the clip rightwards so it starts at 15 seconds
4. create a point label at the beginning of the clip
5. Stretch the clip leftwards from its right edge until it disappears
6. release the mouse button
7. try to stretch the minimal clip rightwards
8. Observe:  you can't
9. zoom in as far as you can
10. Observe: a zero length clip - BUT with a chirp waveform showing
11. try to stretch the minimal clip rightwards
12. Observe:  you still can't

### Expected behavior
Either the minimal clip should be able to be stretched out again - or ist should be removed completely in this use case (there should not be this residual minimal clip)

### Actual behavior
**Step 5**
![image](https://github.com/audacity/audacity/assets/50205984/4ec75bee-f887-4a0c-9425-cc35de90d3d5)

**Step 10**
![image](https://github.com/audacity/audacity/assets/50205984/fcf291fe-b4a9-40e7-af7b-a59211afe014)

### Audacity Version
Latest 3.4.0 alpha

### Operating system
Windows 10 but assume all OS

### Additional context
Flagging @saintmatthieu @LWinterberg @crsib

**Comment by petersampsonaudacity** [comment]
Similar happens when you use smart clips rather than stretchiness - but with this at Step 10 you get a 2-sample length residual (and a selection which extends beyond the two samples:
![image](https://github.com/audacity/audacity/assets/50205984/45c73978-b360-4029-9bf4-05122219e32e)

You can't use smart clip drag to restore it to larger size - but oddly you can stretch it rightwards

**Comment by saintmatthieu** [comment]
Thanks for your report, @petersampsonaudacity !
Unfortunately I cannot reproduce. Would you care for a call ? Would be the occasion to say hi, too.

**Comment by saintmatthieu** [comment]
Will do that tomorrow, here in Germany is dinner time :D

**Comment by petersampsonaudacity** [comment]
> Will do that tomorrow, here in Germany is dinner time :D

First thing 10am German time 9am UK time or late afternoon would be better as I plan to be out on my motorcycle tomorrow.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu  ACK

**Comment by dozzzzer** [comment]
A few notes from me:

- I couldn't reproduce the very last issue from step 12 – the inability to stretch the minimal-length clip – In my case it  stretches just fine
- As for step 10, indeed the length is zero _milliseconds_, which is correct, but if you switch to the display format with samples, you'll see that the length of the clip is 2 samples, which is also correct
- That said, from my standpoint, the only real concern out of three is the inability to expand the minimal-length clip, which is a rather unlikely scenario anyway. For that reason, I reckon P4 would be a fairer tag for it.

@petersampsonaudacity @LWinterberg

**Comment by dozzzzer** [comment]
Fixed by https://github.com/audacity/audacity/pull/5043

**Comment by saintmatthieu** [comment]
> Fixed by https://github.com/audacity/audacity/pull/5043

Following up on this.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

Well they can be retrieved if you zoom in far enough to see them.

**_BUT_** the basic problem remains that you van have what are effectively almost "invisible" clips that are very hard to spot.

A simple use case for this is Steps 1-5 in the STR above (and see image in Actual Behavior.

@Tantacrul had a project recently that had several of these invisible cliplets (as he called them) these were blocking paste activities IIRC

**Comment by saintmatthieu** [comment]
> @Tantacrul had a project recently that had several of these invisible cliplets (as he called them - and I love that nomenclature) these were blocking paste activities IIRC

If that's the project I think, I debugged it no later than this morning. It had 0-length clips, which indeed can be in the way of moving other clips. Could it be that those clips are _all_ the invisible clips you mention? (Not intending to minimize the importance of this enhancement request.)

**Comment by saintmatthieu** [comment]
That aside, I apologize for having closed this request. #5043 doesn't address it.
