### ISSUE TITLE
Current Master does not build on Arch Linux

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5419]
### Bug description

Right now the current master branch does not build on Linux. 
It looks like a Conan issue, and here is a snippet of the build log:
```
-- Check size of float - done
-- ========== Using system version of ZLIB ==========
-- ========== Using system version of EXPAT ==========
-- ========== Using system version of PNG ==========
-- ========== Using system version of JPEG ==========
-- ========== Using Conan version of wxWidgets ==========
-- ========== Using system version of libmp3lame ==========
-- ========== Using system version of mpg123 ==========
-- ========== Using system version of libid3tag ==========
-- ========== Using system version of WavPack ==========
-- ========== Using system version of Ogg ==========
-- ========== Using system version of FLAC ==========
-- ========== Using system version of Opus ==========
-- ========== Using system version of opusfile ==========
-- ========== Using system version of Vorbis ==========
-- ========== Using system version of SndFile ==========
-- ========== Using system version of PortAudio ==========
-- ========== Using system version of RapidJSON ==========
-- ========== Using Conan version of PortMidi ==========
-- ========== Using system version of Catch2 ==========
-- Found libuuid: 
        libuuid_INCLUDE_DIR: /usr/include
        libuuid_LIBRARIES: /usr/lib/libuuid.so
'/usr/bin/python3.11' '/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py' '--build-dir' '/mnt/int/system/aur/audacity-local-git/src/build' '--compiler' 'GNU' '--compiler-version' '13.2.1' '--build-types' 'Release' '--target-arch' 'x86_64' '--build-arch' 'x86_64' '--lib-dir' 'lib/audacity' '-o' 'use_wxwidgets=True' 'use_jack=True' 'use_portmidi=True'
Traceback (most recent call last):
  File "/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py", line 11, in <module>
    from utils.files import safe_rm_tree
ModuleNotFoundError: No module named 'utils.files'
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:209 (message):
  Conan failed to install dependencies (1) /usr/bin/python3.11
Call Stack (most recent call first):
  CMakeLists.txt:578 (include)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in prepare().
    Aborting...
[evert@Evert audacity-local-git]$ python --version
Python 3.11.5
[evert@Evert audacity-local-git]$ 
```

### Steps to reproduce

Run Arch Linux
Build audacity-local-git from the AUR.

### Expected behavior

A clean build. 

### Actual behavior

Build failure, as described in the description. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I deleted the .conan2 cache and the source build directory, but it seems that this is not just a dirty cache. I'll keep on trying to build, just in case it's a transient issue with Conan2

About my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by crsib** [comment]
Well, this is not a Conan issue. For some reason yours Python can't run the code

**Comment by evertvorster** [comment]
I have been banging my head on the table with this one for a while now. 
Which python package provides utils.files?

**Comment by evertvorster** [comment]
OK, I got it to build now. Thanks for looking into it. Turns out I had some old python cache laying about my system.

**Comment by evertvorster** [comment]
Dang it. I am running into this very same issue again, and forgot how I fixed it last time. I'll have to be more descriptive in my fixes!

**Comment by crsib** [comment]
I wonder if this is related somehow to 
```
sys.dont_write_bytecode = True
sys.path.append(os.path.join(os.path.dirname(__file__), '..', "scripts"))
```
in the script. Could it be that the __file__ points to a wrong location?

**Comment by evertvorster** [comment]
Thanks for looking into this... it is still baffling to me. To be honest, I slept on this issue, but still no new ideas this morning. 

How do I check where the "file" is pointing to, and more importantly, what should it be, and how to update it?

**Comment by crsib** [comment]
Well, you can add `print(__file__)` right below that line and see what it shows. You can remove `sys.dont_write_bytecode = True` and see if it helps

**Comment by evertvorster** [comment]
Hi there, thanks for replying to a closed bug report from long ago. 
I tried your suggestion, and this is the output:
```
[evert@Evert conan]$ pwd
/mnt/int/system/aur/audacity-local-git/src/audacity/conan
[evert@Evert conan]$ nano conan_runner.py 
[evert@Evert conan]$ python conan_runner.py 
/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py
Traceback (most recent call last):
  File "/mnt/int/system/aur/audacity-local-git/src/audacity/conan/conan_runner.py", line 12, in <module>
    from utils.files import safe_rm_tree
ModuleNotFoundError: No module named 'utils.files'
[evert@Evert conan]$ 
```

Unfortunately, it does not leave me any the wiser. What is that file variable supposed to be?

I have completely re-installed all the packages on my system, as well as checked that there are no untracked files on my installation, and still this issue persists. I'll try to build it in a clean chroot and see if that works....

**Comment by evertvorster** [comment]
Ahah! I found the problem. 

Firstly, I read about how if there is another utils directory on the path, python stops looking there. 

Then I inserted a print(sys.path) after the append statement. 

Then one by one, did a ls | grep utils in each of the directories listed in the path. 

In my /usr/bin/python/site-packages there was a utils directory, helpfully put there by a game called Singularity, which uses a bit of python in the background. 

I uninstalled Singularity, and now Audacity is building normally.

In the autopsy of this thing, it is not inconceivable that a another package might make a directory called 'utils' somewhere in the path. To avoid this sort of thing happening in the future maybe rename the directory to audacity_utils, or conan_utils, or put it in the start of the path statement so that it is found first.

**Comment by evertvorster** [comment]
I submitted a bug report to Singularity, because putting a 'utils' subdirectory somewhere in the system path for python is asking for trouble. 

It might also explain some other failures I have been seeing in unrelated software. 

Since the issue is sorted on my side, I'm a little mystified as to why this report was re-opened. From my side, I'm quite happy to close it, but if you feel it should be open for whatever reason that is cool too.

**Comment by crsib** [comment]
I think it should be fixed from our side as well. Thank you for your amazing detective work!

**Comment by b1tfl0w** [comment]
Hello, I get this very same problem on Ubuntu 20.04, but I can't solve it, I had singularity game installed which now I removed it, I also did a `sudo apt autoremove` but I still get the error:

```
cmake -G "Unix Makefiles" ../audacity -DCMAKE_BUILD_TYPE=Release
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Build Info:
--   Host System: Linux-5.4.0-173-generic
--   Host System Name: Linux
--   Host System Processor: x86_64
--   Host System Version: 5.4.0-173-generic
--   Host System Architecture: 64-bit
-- 
--   Compiler: /usr/bin/c++
--   Compiler Version: 9.4.0
--   Compiler Standard: 17
--   Compiler Standard Required: ON
--   Compiler Extensions: 
-- 
--   Current Commit: 9dd60f25c
-- 
-- ========== Using Conan version of ZLIB ==========
-- ========== Using Conan version of PNG ==========
-- ========== Using Conan version of JPEG ==========
-- ========== Using Conan version of EXPAT ==========
-- ========== Using Conan version of wxWidgets ==========
-- ========== Using Conan version of libmp3lame ==========
-- ========== Using Conan version of mpg123 ==========
-- ========== Using Conan version of libid3tag ==========
-- ========== Using Conan version of WavPack ==========
-- ========== Using Conan version of Ogg ==========
-- ========== Using Conan version of FLAC ==========
-- ========== Using Conan version of Opus ==========
-- ========== Using Conan version of opusfile ==========
-- ========== Using Conan version of Vorbis ==========
-- ========== Using Conan version of SndFile ==========
-- ========== Using Conan version of PortAudio ==========
-- ========== Using Conan version of RapidJSON ==========
-- ========== Using Conan version of PortMidi ==========
-- ========== Using Conan version of vst3sdk ==========
-- ========== Using Conan version of Catch2 ==========
-- Found libuuid: 
	libuuid_INCLUDE_DIR: /usr/include
	libuuid_LIBRARIES: /usr/lib/x86_64-linux-gnu/libuuid.so
'/usr/bin/python3.9' '/home/sasha/src/audacity/conan/conan_runner.py' '--build-dir' '/home/sasha/src/audacity-build' '--compiler' 'GNU' '--compiler-version' '9.4.0' '--build-types' 'Release' '--target-arch' 'x86_64' '--build-arch' 'x86_64' '--lib-dir' 'lib/audacity' '-o' 'use_zlib=True' 'use_libpng=True' 'use_libjpeg-turbo=True' 'use_expat=True' 'use_wxwidgets=True' 'use_libmp3lame=True' 'use_mpg123=True' 'use_libid3tag=True' 'use_wavpack=True' 'use_ogg=True' 'use_flac=True' 'use_opus=True' 'use_opusfile=True' 'use_vorbis=True' 'use_libsndfile=True' 'use_jack=True' 'use_portaudio=True' 'use_rapidjson=True' 'use_portmidi=True' 'use_vst3sdk=True' 'use_catch2=True'
Traceback (most recent call last):
  File "/home/sasha/src/audacity/conan/conan_runner.py", line 11, in <module>
    from utils.files import safe_rm_tree
ModuleNotFoundError: No module named 'utils.files'
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:209 (message):
  Conan failed to install dependencies (1) /usr/bin/python3.9
Call Stack (most recent call first):
  CMakeLists.txt:579 (include)


-- Configuring incomplete, errors occurred!
See also "/home/sasha/src/audacity-build/CMakeFiles/CMakeOutput.log".
See also "/home/sasha/src/audacity-build/CMakeFiles/CMakeError.log".

```

**Comment by evertvorster** [comment]
You will have to do the same legwork, first, find a directory named utils in your system, then figure out which bit of software put it there. Since I am not familiar with your distrobution, I can't tell you how to figure out which package installed that file,  but yours is a popular distrobution, so google is your friend. 

Of course, the fix for this bug went in after 3.4.2 was released, so you might be able to just build master. It's fairly usable now... YMMV
