### ISSUE TITLE
Crossfade Track bugs

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5483]
### Steps to reproduce

Testing with either a couple of mono of tracks or couple of stereo tracks.
For example mono tracks:
![image](https://github.com/audacity/audacity/assets/11887021/29fcdb97-30ef-452c-b245-c588d918e732)

Case A:
Two mono tracks, no time stretching.

Case B:
Two mono tracks, time stretching.

Case C:
Two stereo tracks.

Case D:
stereo tracks with time stretching

### Expected behavior

Case A:
The same as the actual behaviour. No problem here.

Case B:
Something like the actual behaviour of case A:

Case C:
Something happens.

Case D:
Something happens.

### Actual behavior

Case A:
![image](https://github.com/audacity/audacity/assets/11887021/2d25be91-445c-4084-8ce3-9a235608d4ab)

Case B:
![image](https://github.com/audacity/audacity/assets/11887021/903ce3fd-09b8-4205-80f1-7280180febe8)

Case C:
The effect has no effect.
![image](https://github.com/audacity/audacity/assets/11887021/b25ea149-92fc-4c6b-b75e-ef89f32dc900)

Case D:
The effect has no effect.
![image](https://github.com/audacity/audacity/assets/11887021/04ead069-7704-4522-a88a-1912a65346be)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by crsib** [comment]
I wonder if it is a duplicate of #5471

**Comment by DavidBailes** [comment]
> I wonder if it is a duplicate of #5471

This is the crossfade tracks effect, rather than the crossfade Clips effect.

**Comment by crsib** [comment]
@saintmatthieu ^^

**Comment by saintmatthieu** [comment]
There are at least two problems:
1. cross-fading clip and track commands on unstretched clips - #5486 should fix this and it should be easy.
2. some imprecision when applying an effect to stretched data ; this is caught by a sanity check in `crossfadeclips.ny` which cancels the effect.
3. the error returned by this sanity check is sometimes not shown to the user, resulting in like nothing happened (cases C and D reported by @DavidBailes )

**Comment by saintmatthieu** [comment]
@chinakov Works for me. I guess you might have tested with the build of the second-last commit, where this bug was indeed not yet fixed. The one you should test with is https://github.com/audacity/audacity/actions/runs/6775595176. Could you double-check?

**Comment by chinakov** [comment]
Hmm, very strange. Still doesn't work from the run you've attached. I've double checked and it was most certainly the version I've downloaded.

![image](https://github.com/audacity/audacity/assets/139755141/57cdedf8-a1fa-4a5e-a78b-aa13d4608a06)


![image](https://github.com/audacity/audacity/assets/139755141/691727a6-1efa-47b3-a7d0-6ade27e799bf)

**Comment by chinakov** [comment]
Alrighty, so I've cleared out the Audacity folders within %localappdata% and %roamingappdata%, and the issue has went away. It seems that the broken plug-in was somehow cached by Audacity, and was called during the testing.

I will have a good think on this, as I really hope this can't affect real users and only applies to some extreme testing scenarios where there's 1000's of different versions used on the same computer, installers and portables alike.

**Comment by saintmatthieu** [comment]
Thanks @chinakov !
