### ISSUE TITLE
View scrolls to first track on importing audio file

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6361]
### Bug description

Bug reported here: https://forum.audacityteam.org/t/adding-files-but-sending-me-to-the-top/105025

> when I add new files to my project, the new Audacity is sending me back to the start (top) of the project instead of keeping me where the new files are. It’s not a huge problem as I can use the bar on the right to scroll down to the bottom again - it’s just a bit annoying, especially when I’m dealing with over 40 files.
It didn’t do that before I updated to the new version last week.

### Steps to reproduce

Import multiple files one at a time. Scroll down to the bottom after each import.

### Expected behavior

The imported file to be visible at the bottom of the tracks window.

### Actual behavior

The track window scrolls to the top after each import.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Regression against Audacity 3.3.0 (I have only tested this on 3.3 and 3.5).

**Comment by LWinterberg** [comment]
is this fixed by https://github.com/audacity/audacity/pull/6345 ?

**Comment by chinakov** [comment]
@LWinterberg - the issue is still present in https://github.com/audacity/audacity/pull/6345, just checked.

**Comment by Paul-Licameli** [comment]
Is the problem present in 3.5?

**Comment by SteveDaulton** [comment]
> Is the problem present in 3.5?

Yes, but it is not in 3.4.2

**Comment by DDGrim** [comment]
Yeah, this is super annoying.  Putting together a podcast with 60 tracks is an absolute nightmare now. I’ve spent over 4 hours going through settings to see if I can fix this with no luck. Been using Audacity for 12 years without this problem. Please for the love of mankind fix this.

**Comment by dozzzzer** [comment]
@saintmatthieu the issue is still reproducible

https://github.com/audacity/audacity/assets/70063970/0ab5b4da-b4a1-4aca-a4f0-315a243c2578

**Comment by Paul-Licameli** [comment]
Was there any bisection if the problem?  I see a proposed fix that looks like a lot of workaround code added instead of discovery of where the problem entered.

**Comment by dozzzzer** [comment]
@Paul-Licameli no, there wasn't.

**Comment by dozzzzer** [comment]
Tested
