### ISSUE TITLE
Audacity crash upon installing Nyquist Plugins

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6433]
### Bug description

If a User installs a new Nyquist plugin, effect or generator, Audacity will crash upon installing any of them. 

### Steps to reproduce

1. Open Audacity
2. Grab any Nyquist component
3. Install the component via 'Tools -> Nyquist Plugin Installer'
4. Press 'Apply'

### Expected behavior

The Nyquist plugin is installed without any issues.

### Actual behavior

Audacity crashes when installing any Nyquist Plugins.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

I've bisected the introduction of this issue back to when https://github.com/audacity/audacity/commit/983dc1b7c7fd5008fd40420fefe6b63d68cd6a77 got merged. Previous master builds do not exhibit this behaviour.

**Comment by petersampsonaudacity** [comment]
@chinakov  - so is this a regression Anton?

**Comment by petersampsonaudacity** [comment]
Testing on W11 shows this is a regression on 3.5.1

**Comment by chinakov** [comment]
I've traced the particular commit in wave-refactoring-branch that created this issue: it was the last commit in the branch (

**Comment by chinakov** [comment]
This is fixed, thank you!

**Comment by petersampsonaudacity** [comment]
> This is fixed, thank you!

Still fails on latest 3.6.0 alpha master:    audacity-win-3.6.0-alpha-20240517+15e23de-x64-msvc2022
