### ISSUE TITLE
Clicking random key causes playhead field to go invisible

### ISSUE THREAD

**Issue by ebiow** [audacity/audacity#7013]
### Bug description

Clicking on a specific key causes the playhead, the pane with the waveform, to become white, and I couldn't figure out how to make it visible again.

### Steps to reproduce

1. While editing one large track in the latest flatpak stable release (3.6.1) I hit some key, I think it was Page Down, but am not sure, and suddenly the main pane where you can see the track disappeared, or rather, became white. I could still interact with the file and export, but couldn't see anything. I could still click on the timeline and play the track and even export the file but simply saving the track as a AUP and opening it again didn't change the behavior, that pane was still white/invisible.
2. However I found when I went to resize the window by going to the edge of the app and dragging so I could make a screenshot to submit the track reappeared again and seemed to be back to normal. This is very weird behavior I've never seen before, but it happened to me yesterday, also on flatpak 3.6.1 on Debian stable. 

### Expected behavior

The main editing window should not go white. 

### Actual behavior

Now that I know there is a simple fix, dragging the side application a bit, I am not so concerned, but it is worth seeing if other people are having the same experience. It is very off-putting, and I wasted an hour trying to figure out what is going on, messing with menus and starting second instances of audacity. There was nothing in the History to undo. The next time it happens I'll take a screenshot to submit with this report.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by ebiow** [comment]
OK, this is the third machine (all Debian from Flathub) I've had this problem on and the second time it happened while editing a file on this box dragging the side of the application didn't restore field to visibility. Luckily, I was pretty much done editing the file & just exported. 
This is actually a really annoying bug, and it occurs when hitting the Page Down key.
![audacity](https://github.com/user-attachments/assets/32ace594-1fe7-48d2-a6af-8c66b0ca0670)

Attached is an image of how it manifests itself.
![audacity](https://github.com/user-attachments/assets/3b4c5866-a3e4-4712-826d-a1cda95bc8ae)

**Comment by manyet1k** [comment]
This happened to me as well, but not after hitting a key -- the UI randomly goes white after scrolling or zooming in on the timeline. Audacity 3.6.1 Flatpak on Pop!_OS 22.04

**Comment by aisuneko** [comment]
Same problem here, random UI crash. A temporary workaround is to go to Settings - Interface and switch to another UI theme, but the problem will persist shortly after. Audacity 3.6.1 from official Arch Linux repo

**Comment by aisuneko** [comment]
I think #6959 #6976 is relevant to this; Will test after 3.6.2 is packaged for Arch

**Comment by nalin243** [comment]
Happening to me as well. It just goes away if you resize the window for me.

**Comment by ebiow** [comment]
> Same problem here, random UI crash. A temporary workaround is to go to Settings - Interface and switch to another UI theme, but the problem will persist shortly after. Audacity 3.6.1 from official Arch Linux repo

That didn't work for me. I tried all the themes. And after I tried switching themes I noticed the menu bar also turned white unless I moused over it, even when I returned to my normal Light theme. 

The only thing to do was export my files and then start editing the rump file that I hadn't already treated.

Anyone have an idea when 3.6.2 will hit the repositories? In the mean time I'll purge the Debian testing audacity 3.6.1 deb file & the flatpak version that I use on Debian testing & stable respectively & just use the 3.5.1 appimage version until this gets sorted out. I think 3.5.1 was the last flatpak version that didn't randomly corrupt the GUI.

**Comment by ebiow** [comment]
Wonderful. On the Debian testing 3.6.1 I got whited out. So I exported audio and tried opening the audacity-linux-3.5.1-x64.AppImage instead. While it works fine with Debian stable it won't open on Debian Trixie. 
```
$ bin/audacity-linux-3.5.1-x64.AppImage 
/lib/x86_64-linux-gnu/libatk-1.0.so.0
/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
/lib/x86_64-linux-gnu/libcairo-gobject.so.2
/lib/x86_64-linux-gnu/libcairo.so.2
/lib/x86_64-linux-gnu/libgio-2.0.so.0
/lib/x86_64-linux-gnu/libglib-2.0.so.0
/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
/lib/x86_64-linux-gnu/libgobject-2.0.so.0
/lib/x86_64-linux-gnu/libgthread-2.0.so.0
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libpixman-1.so.0
findlib: libportaudio.so: cannot open shared object file: No such file or directory
/home/ed/bin/audacity-linux-3.5.1-x64.AppImage: Using fallback for library 'libportaudio.so'
/tmp/.mount_audaci2y0fvw/bin/audacity: /tmp/.mount_audaci2y0fvw/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_audaci2y0fvw/bin/audacity: /tmp/.mount_audaci2y0fvw/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
```
Other people with newer distros are [having the same issue](https://github.com/audacity/audacity/issues/7127), which is apparently fixed with version 3.7. 

One of the main reasons I upgraded to Testing was to get a newer version of audacity (which has some advantages over the older 3.2.4+dfsg-1 on Debian stable. I can't downgrade to Debian stable. The flatpak 3.6.1 version is similarly buggy. I had to export 3 times to finish editing a single big file. This is 10% less than fun. 

Does anyone know how to install a 3.5.x version of the audacity flatpak?

**Comment by ryliejamesthomas** [comment]
Like others, I mostly notice this when scrolling the timeline, but I've also just encountered it repositioning a clip with the mouse, even though it wasn't causing any scrolling.

**Comment by dozzzzer** [comment]
@ebiow this is fixed by https://github.com/audacity/audacity/pull/6955

**Comment by aisuneko** [comment]
@dozzzzer Can confirm that this is not fixed yet as of the latest master build (b666fbf). The UI will now immediately crash when built from source using the latest master branch in contrast to stable 3.6.1

**Comment by kryksyh** [comment]
@ebiow that's because of the way we are handling releases, the fix is in 3.6.2 branch, but not in master yet. Could you try 3.6.2 branch?

**Comment by ebiow** [comment]
3.6.2 isn't in the Debian testing repository yet, but the 3.6.2 flatpak seems to be working as expected, no more white-outs. I'll report back if I encounter one.

**Comment by ebiow** [comment]
3.6.2 isn't in the Debian testing repository yet, but the 3.6.2 flatpak seems to be working as expected, no more white-outs. I'll report back if I encounter one.

**Comment by ebiow** [comment]
3.6.3+dfsg-1 is in the Debian testing repos and is working properly.
