### ISSUE TITLE
Exported Mono WAV PCM 16-bit has no sound / is empty / all silent

### ISSUE THREAD

**Issue by mpek** [audacity/audacity#7059]
### Bug description

No sound in it, total silence, blank. Wonder why?
It also took the time to export the full data and processing it, but the result is a file with the size as if it has data in it, but when played back or imported to Audacity you can hear that there is nothing. 

Exporting the Mono file as Stereo gets exported correctly and plays back with sound in it. 

### Steps to reproduce

The source file is Mono. Around two hours long. It was imported through ffmpeg as it was part of a mkv container. 
Realtime effects used are Compressor and Limiter on master. That's all. 
Format: WAV (Microsoft)
Sample Rate: 48000 Hz
Encoding: Signed 16-bit PCM
Export Range: Entire Project

### Expected behavior

Audio should be present in exported Mono file.

### Actual behavior

The exported file has no sound in it.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by LWinterberg** [comment]
is this #7002 and fixed by https://github.com/audacity/audacity/pull/7055 ?

**Comment by mpek** [comment]
Thank you for our answer. 

#7055 Does not offer a fix as mono or stereo channel maps are available during export dialog. 
Mono exports silence, Stereo exports everything ok, but the Mono source file should stay Mono on export. 
It's similar to #7002 but in this case only using built in effects, whereas in #7002 external plugins are being used.

**Comment by dozzzzer** [comment]
Please try [the build](https://github.com/audacity/audacity/actions/runs/10282303222?pr=7055), rather than making assumptions about what this PR does and doesn't fix based on its description. 😄 I've just tried it and it looks like your problem is no longer reproducible.
