### ISSUE TITLE
Audacity 3.6.1 uses an enormous amount of temporary file space

### ISSUE THREAD

**Issue by older-pack** [audacity/audacity#7211]
### Bug description

I have a two hour radio program as an MP2 audio file.
It's 128kbps and is 118MB in size.
Audacity couldn't load it as my `/var` folder ran out of space!

Looking into it:
My `/var/tmp` directory is on a 10 GB disk with ~6GB available

I halved the MP2 file to ~57 mins (55MB still at 128kbps)
Audacity was able to load that.

Examining Audacity's `/var/tmp/audacity...` usage for the 55MB MP2:

It uses a staggering 2.8G disk space!

That's **four** times the WAV size of the audio. :open_mouth:

A CD quality WAV of the file is only 665MB

There is something *very* wrong with your use of temporary disk space.

### Steps to reproduce

Load a similar sized file

### Expected behavior

The temporary file should not be **four** times the WAV of the same file. 

### Actual behavior

The `/var/tmp/audacity...` directory is huge: 2.8GB for a 55MB .MP2

### Audacity Version

current master / alpha / nightly build
Audacity 3.6.1

### Operating system

Linux

### Additional context

```
Debian trixie x86_64 
Kernel: 6.10.4-amd64 
GNOME 46.4
```

**Comment by LWinterberg** [comment]
and just to be clear, you have just loaded it in? so no undo history of any kind yet?

**Comment by older-pack** [comment]
Correct.

`/var/tmp/audacity...` is empty before I load the file.

When I load the file the directory gets populated with three files:

```
New Project 2024-08-29 20-18-04 N-1.aup3unsaved      1,348,468,736 bytes
New Project 2024-08-29 20-18-04 N-1.aup3unsaved-shm        196,608 bytes
New Project 2024-08-29 20-18-04 N-1.aup3unsaved-wal  1,598,483,952 bytes
```

When I close the project and exit Audacity `/var/tmp/audacity...` gets emptied.

**Comment by dozzzzer** [comment]
I managed to reproduce it on MacOS and Windows.

**Comment by marcelloromani** [comment]
Audacity 3.6.4
MacOS Sequoia 15.0
WAV file: 958 MiB, Audio format: 48 kHz / 24 bit
New Audacity project -> File -> Import Audio -> File -> Save project
AUP3 file size: 1.29 GiB, ~70 MiB more.

I am not sure how to check for the equivalent of /tmp space used up on Mac OS...

Have you tried importing your file with 3.6.4?

**Comment by kryksyh** [comment]
@older-pack this issue was fixed in 3.6.4 (see #7312)

**Comment by kryksyh** [comment]
Sorry, after reading more carefully it looks like it is a different issue. Could you share the source audio file with us? I can't reproduce the issue with a couple mp2 files that I have.

**Comment by older-pack** [comment]
It's still happening on 3.6.4

Check `/var/tmp/audacity...`
Empty

Launch Audacity.
There is no need for my original MP2.
Just generate a 60 min audio file.
```
Generate > Noise
	White
	Amplitude 0.8
	Duration 60 mins
```

Check  `/var/tmp/audacity...`
```
New Project 2024-10-05 05-33-58 N-1.aup3unsaved      643,366,912
New Project 2024-10-05 05-33-58 N-1.aup3unsaved-shm  98,304
New Project 2024-10-05 05-33-58 N-1.aup3unsaved-wal  643,602,552
```
That's 1,287,067,768 bytes!

Export generated audio as a WAV
```
Sample rate 44100Hz
Signed 16bit PCM
```

Check that WAV's size
`export.wav 317,520,044 bytes`.

Close Audacity.

Check `/var/tmp/audacity...`
Empty again.

Re-open Audacity
Load the exported WAV

Check `/var/tmp/audacity...`
```
New Project 2024-10-05 05-50-30 N-1.aup3unsaved      643,366,912
New Project 2024-10-05 05-50-30 N-1.aup3unsaved-shm       98,304
New Project 2024-10-05 05-50-30 N-1.aup3unsaved-wal  762,593,952
```

Which is 1,406,059,168 bytes 


**Summary:**
WAV is 320 MB
When it's loaded in Audacity `/var/tmp/audacity...`  is 1.4GB
