### ISSUE TITLE
[AU4] Audacity crashes when quitting with some unsaved changes

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7290]
### Description

1. Load up any .aup3 project
2. Make some changes, e.g. copy & paste a clip
3. Cmd + Q or quit by clicking the red "x" icon
4. Observe: Audacity crashes

**Comment by avachon100510** [comment]
I think it also happens on Windows, have you tested it out?

**Comment by Eism** [comment]
I fixed it in #7283, please retest on last master build

**Comment by dozzzzer** [comment]
@Eism testing the recent master build shows that the issue remains:

https://github.com/user-attachments/assets/54a63150-9a1c-4229-8ac9-7da9799dc477

**Comment by dozzzzer** [comment]
@avachon100510 Yes I have tested on Windows 11, and I do not see the crash.

**Comment by JoeS209** [comment]
In #7310 I fixed some lifetime issues with scroll bars when a window is closed.  You might try testing with the latest code.

**Comment by avachon100510** [comment]
> @avachon100510 Yes I have tested on Windows 11, and I do not see the crash.

Good to know, just making sure it was a platform-exclusive bug.

**Comment by dozzzzer** [comment]
to be re-chcecked

**Comment by dozzzzer** [comment]
Not reproducible anymore
