### ISSUE TITLE
Acces violation exec, can't save .aup3 closing the program

### ISSUE THREAD

**Issue by A22PG** [audacity/audacity#7351]
### Bug description

I have a problem with the latest version of Audacity; for some reason, when I try to close the program, Audacity gives me an *`EXCEPTION_ACCESS_VIOLATION_EXEC`* and Audacity doesn't merge `.aup3-shm` and `.aup3-wal` with `.aup3` file. If I try to restaure the file, Audacity saves my project and deletes `.aup3-shm` and `.aup3-wal`.
[crashReport.txt](https://github.com/user-attachments/files/17031805/crashReport.txt)

### Steps to reproduce

1. Open a `.aup3` file
2. Make changes to the file (for example, delete a part)
3. Go to close program (`X` button, top right on the *Windows 10* title bar)
4. Save changes

### Expected behavior

* Changes made should be saved correctly
* Audacity should delete `.aup3-shm` and `.aup3-wal` files

### Actual behavior

An error that I can't send together with `.aup3-shm` and `.aup3-wal` files without merge to `.aup3`

https://github.com/user-attachments/assets/45f871ae-532a-4ec4-a6b9-7733786ab320

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

In the folder I have a restriction that only I as a user can modify it; however, **this restriction has been in the folder for years and has never been a problem for me before until this last version** (even other programs save the files without giving any error)

![folderSecurity](https://github.com/user-attachments/assets/f7c29850-b09a-4b04-8fd4-f33d068da631)

**Comment by LWinterberg** [comment]
this likely is fixed in 3.6.4

**Comment by A22PG** [comment]
Hi again,

Unfortunately, I’m still experiencing this same issue in Audacity v3.7.3.

The crash continues to happen randomly on exit, both with the same project and across different ones. It’s difficult to reproduce consistently, but it follows the same pattern as before — the application closes normally most of the time, but occasionally crashes with an `EXCEPTION_ACCESS_VIOLATION_READ` error.

I’ve attached a new `error.txt` log generated during one of these crashes. According to what I’ve been able to investigate a little, the stack trace shows a failure in `wxbase313u_vc_custom.dll`.

Could this issue be reopened, or should I open a new one to report that it still persists?

Thanks in advance!

P.S.: The "Send crash" button in the log produces an error and doesn't send the report, so I have to send it via `.txt` file.

[error.txt](https://github.com/user-attachments/files/19623169/error.txt)
