### ISSUE TITLE
[AU4] Tone generator

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#7369]
### Description

Implement the UI and interactions of the Tone generator in AU4. Should behave like AU3's.

**Comment by chinakov** [comment]
Tested, thanks!

**Comment by dozzzzer** [comment]
@saintmatthieu @chinakov I don't think it's ready to be merged yet. Here's why:

- After generating a tone of a certain duration, the next time you open up the dialog, you see a different duration value.

https://github.com/user-attachments/assets/3985afe5-6392-4ecd-bfb7-a178ddad2f47

- Tone generator disregards the cursor position, which results in the wrong clip start time (see how the cursor is at the zero time mark but the clip is generated later):

https://github.com/user-attachments/assets/aed19a16-eb9b-4799-b27a-d9ae6b9d2564

- After generating into an empty track, deleting a clip and then generating once more, it either doesn't do anything or  simply creates a new empty track underneath and doesn't generate any tone.

https://github.com/user-attachments/assets/731f51a7-a9e3-41b5-adac-c247e3c639a3

https://github.com/user-attachments/assets/6e9430c9-fe23-428f-96c8-36c546e91c94

- Duration text input doesn't correctly react to the digits input. In this video, I'm demonstrating it by entering a sequence of ones for every digit and then zeroes, then, again, ones and, lastly, zeroes once again. Observe how the last three digits are misbehaving (the display format, if anything, is hh:mm:ss + milliseconds):

https://github.com/user-attachments/assets/e6e179a4-bd38-4b4e-991a-b5fd4d46d46e

- Sometimes it changes a display format totally out of the blue upon re-opening of the dialog. Observe how `00h00mm00.100s` changes to `00h00mm00s+04410samples`:


https://github.com/user-attachments/assets/a4a53166-290b-4407-81ad-94af2d38def9

**Comment by saintmatthieu** [comment]
@dozzzzer thanks for this comprehensive report!

> After generating a tone of a certain duration, the next time you open up the dialog, you see a different duration value.

Unexpected things I observe besides this:
* you have a track selected, yet the generated tone creates a new track. I can't reproduce this.
* Is it just that I don't see the resulting clip? The generator has created a new track, but it looks empty.

> Tone generator disregards the cursor position, which results in the wrong clip start time (see how the cursor is at the zero time mark but the clip is generated later):

This is a selection thing: the rewind button wasn't tied to a selection change. It will be in one of my fix commits. Thanks!

> After generating into an empty track, deleting a clip and then generating once more, it either doesn't do anything or simply creates a new empty track underneath and doesn't generate any tone.

This is another thing that has to be changed about selection. At the moment, selecting a clip's header resets the selection to nothing, instead of setting the selection to a point selection based on the position of the cursor. I have to fix this, too. @grliszas14 FYI.

**Comment by saintmatthieu** [comment]
> Duration text input doesn't correctly react to the digits input.

Indeed, fix coming up, thanks!

**Comment by saintmatthieu** [comment]
@dozzzzer please re-test in its entirety.

I rebased on @grliszas14 's selection branch, which contains fixes to part of the bugs you've identified.
The other part I've fixed in this very PR.
Note to one of your remarks:
> Sometimes it changes a display format completely out of the blue upon re-opening of the dialog. Observe how 00h00mm00.100s changes to 00h00mm00s+04410samples:

I don't think this is a bug. It behaves that way in AU3 as well. You first generate a tone without a selection: the proposed format is hh:mm:ss + milliseconds. Once you've generated the tone, it is automatically selected. Then, when re-opening the generator, it detects that you have a selection, and hence calibrates to generate exactly the selection's duration, which necessitates the hh:mm:ss + milliseconds format.

**Comment by chinakov** [comment]
>>Tone generator disregards the cursor position, which results in the wrong clip start time (see how the cursor is at the zero time mark but the clip is generated later):

>This is a selection thing: the rewind button wasn't tied to a selection change. It will be in one of my fix commits. Thanks!

It seems that there's still an issue connected to this, if the User drags the playhead cursor, the tone generator makes the clip align with the previous playhead position.
