### ISSUE TITLE
Deleting a fractional number in an effect's text box by pressing Backspace doesn't work correctly

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7925]
1. Put the cursor at the very end
2. Start pressing Backspace and observe how the number is changing

![2024-12-17_13-54-40 (1)](https://github.com/user-attachments/assets/c05ab138-25c8-4491-a2e1-907fef5e08bf)

**Comment by dozzzzer** [comment]
@embarc-gabriel Two issues regardless of the platform are found:

1. When deleting the last digit in the fractional part by pressing the Backspace once, the calculated new amplitude value is wrong
2. After deleting the amplification value completely by pressing the Backspace key and then pressing Esc, Audacity crashes

https://github.com/user-attachments/assets/1ffa5616-44fc-4e7e-ac24-9fc43fdb62c4

**Comment by igorkorsukov** [comment]
@dozzzzer please test this build https://github.com/audacity/audacity/pull/8050 
if everything is ok in editing the amp value, then I will extend this solution to other forms of effects

**Comment by dozzzzer** [comment]
@igorkorsukov #8050 fixes the issue

**Comment by kryksyh** [comment]
The issue is not correctly solved in `master`, RealInputField.currentValue become unbound on edit.

https://github.com/user-attachments/assets/5d42f25c-1625-4848-9588-ddbbe73da450

And changes made in #8565, are restoring the issue in its original form, fixes are needed to `IncrementalPropertyControl`

**Comment by chinakov** [comment]
This is still reproducible on the latest master: b4cf81fdb73aa0464f4a6e47fddee1695fb28043

**Comment by chinakov** [comment]
This is still reproducible on the latest Master (6a2ccc6bae123089f852ee22b47c819118b94211)

**Comment by dozzzzer** [comment]
Cannot reproduce anymore
