### ISSUE TITLE
Cursor visual glitch when playback is active (Windows)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#8810]
https://github.com/user-attachments/assets/97d80dbe-e2b7-4bbb-988d-f8de316fcb93

**Comment by dozzzzer** [comment]
to be reproduced on non-VM Windows machine after https://github.com/audacity/audacity/issues/8820 is fixed

**Comment by dozzzzer** [comment]
Still reproducible; however, only when the display scaling is set to > 100%

**Comment by chinakov** [comment]
This is still reproducible on the latest Master (f7034596fe9f5df9d605c52ddc4196ffee3a15b0)

**Comment by luapmartin** [comment]
I do think that would be fixed by #9613

**Comment by luapmartin** [comment]
not yet, it's still happening, but we are getting closer

**Comment by dozzzzer** [comment]
@luapmartin Yeah, it's still there. At a higher rate, though.

https://github.com/user-attachments/assets/bb699682-9a5a-48a3-a43a-c93b0cb8e333

**Comment by saintmatthieu** [comment]
Was closed automatically when merging #9613 , as it had a tentative "Resolves" for this issue (but in the end it didn't resolve it.)

**Comment by dozzzzer** [comment]
Tested. It's still flickering ever so slightly, but I think it's negligible.
