### ISSUE TITLE
Change track sample rate from context menu

### ISSUE THREAD

**Issue by embarc-gabriel** [audacity/audacity#8985]
### Description

Enable this feature on the context menu

**Comment by dozzzzer** [comment]
@embarc-gabriel 

1. After changing the track's sample rate to a custom one (e.g. 44095 Hz), it does correctly read in the track's context menu, but when you click "Other" it summons the dialog where it still reads "44100 Hz";
2. The title bar of the dialog "Set Rate" should be changed to sentence-case: "Set rate"

https://github.com/user-attachments/assets/f8b1835b-1e66-48ea-9377-ee039d5060bc

3. The context menu items should be "Other...", implying that it will open up a new dialog (same as in AU3):

<img width="356" height="316" alt="Image" src="https://github.com/user-attachments/assets/d57faebd-44fc-4df8-877d-d512210ac87a" />

<img width="435" height="290" alt="Image" src="https://github.com/user-attachments/assets/c71a9a25-f0c6-47dc-b594-b487606e3e3b" />

**Comment by embarc-gabriel** [comment]
@dozzzzer this should be fixed on the latest build.

**Comment by dozzzzer** [comment]
The last issue remains unfixed, although since it's really minor, I'll log it as a separate ticket to not block the PR from merging: https://github.com/audacity/audacity/issues/9075

**Comment by embarc-gabriel** [comment]
@dozzzzer on figma there is no elipsis https://www.figma.com/design/THwxq4Q8SBU4mHgIILmdU1/20---Menus?node-id=4045-739&p=f&t=9tY4PBVE8weqk32z-0
Should I add it anyway.

**Comment by dozzzzer** [comment]
@embarc-gabriel yes please
